Implement feature card today lecture
buku-masjid/buku-masjid pull request #11
Opened 2023-09-16 09:54 UTC by andriawan

Halo mas @nafiesl, semoga sehat selalu.

Saya tertarik untuk kontribusi pada produk opensource buku masjid ini. PR ini merupakan langkah awal saya untuk bisa bersama-sama berkontribusi ke opensource. Semoga bermanfaat. PR ini berkatian dengan Issue #9 

Secara teknis, saya coba mengimplementasikan card pengajian hari ini, dalam bentuk komponen livewire. Konsepnya mirip dengan screenshot dan definisi task dari mas @nafiesl. Sedikit saya tambahkan carousel untuk multiple schedule seperti demo pada video di bawah. Tujuannya ialah agar lebih simpel secara UI dan pengguna bisa lebih fokus secara UX.
Saya juga coba menerapkan test agar fitur ini makin baik dan mudah dalam refactoring kedepannya.

https://github.com/buku-masjid/buku-masjid/assets/13099373/68feab36-9204-4c90-8285-11c981f419d9

Beberapa kode ada yang duplikat karena livewire tidak bisa akses kode-kode yang ada pada basecontroller. Mohon saran dan feedback jika ada kode kurang baik, berpotensi improvement maupun kode yang membingungkan. Sekali lagi, semoga produk ini bermanfaat banyak bagi umat.

2023-09-16 12:43 UTC, nafiesl commented
Halo mas @andriawan. Alhamdulillah terima kasih mas ut kontribusinya.

Saya akan lihat lebih detail dan tes PR ini. Tetapi barusan saya lihat sekilas mas. Ada beberapa catata yang mungkin bisa mas koreksi dulu.

1. Di PR ini ada perubahan terkait laravel sail yang tidak relevan dengan task di issue #9. Saya berharap bagian ini dibuat dengan PR terpisah mas. Jadi PR ini khusus perubahan terkait dengan jadwal pengajian hari ini.
2. Di sini ada tambahan seeder untuk create record lecturing schedule. Ini bisa dihapus saja mas. Nanti di task lain insyaallah kita akan buat secara khusus seeder untuk data demo, utk mempermudah kontributor.

Selanjutnya akan saya tes PR ini lebih detail, terima kasih mas.

2023-09-16 13:54 UTC, andriawan commented
Baik mas @nafiesl akan segera coba saya sesuaikan terkait commit yang tidak relevan

2023-09-16 15:10 UTC, nafiesl requested changes
mas @andriawan ini saya review bagian struktur folder dan penamaan file/class dulu ya mas. Gimana menurut mas?

2023-09-16 15:10 UTC, nafiesl commented on tests/Feature/BerandaPublik/TodayCardLecturingScheduleTest.php
> +namespace Tests\Feature\LecturingSchedule;
Mas @andriawan ini kalau boleh, struktur folder dan nama classnya kita ganti begini:

tests/Feature/Livewire/PublicHome/TodayLecturingSchedulesTest.php

```suggestion
namespace Tests\Feature\Livewire\PublicHome;
```

2023-09-16 15:10 UTC, nafiesl commented on tests/Feature/BerandaPublik/TodayCardLecturingScheduleTest.php
> +class TodayCardLecturingScheduleTest extends TestCase
nama classnya kita ganti gini:
```suggestion
class TodayLecturingSchedulesTest extends TestCase
```

2023-09-16 15:10 UTC, nafiesl commented on app/Http/Livewire/TodayLecturerCard.php
> +namespace App\Http\Livewire;
Untuk class livewirenya kita pakai struktur folder gini coba mas:
```
app/Http/Livewire/PublicHome/TodayLecturingSchedules.php
```
```suggestion
namespace App\Http\Livewire\PublicHome;
```

2023-09-16 15:10 UTC, nafiesl commented on app/Http/Livewire/TodayLecturerCard.php
> +class TodayLecturerCard extends Component
```suggestion
class TodayLecturingSchedules extends Component
```

2023-09-16 15:10 UTC, nafiesl commented on app/Http/Livewire/TodayLecturerCard.php
> +        return view('livewire.today-lecturer-card');
Untuk viewnya ini, kita bisa terapkan struktur folder dan nama file snake_case seperti ini mas:
```suggestion
        return view('livewire.public_home.today_lecturing_schedules');
```

Note:
Kenapa nama view snake_case? Karena lebih mudah select text dengan double click mouse. Sedangkan yang dash-case, dia select text hanya 1 kata saja.

2023-09-16 15:58 UTC, andriawan commented on tests/Feature/BerandaPublik/TodayCardLecturingScheduleTest.php
> +namespace Tests\Feature\LecturingSchedule;
setuju mas @nafiesl, untuk penamaan memang perlu diskusi.

2023-09-16 15:59 UTC, andriawan commented on app/Http/Livewire/TodayLecturerCard.php
> +        return view('livewire.today-lecturer-card');
oke paham mas...nama file tersebut default hasil generate command artisan

2023-09-17 16:05 UTC, nafiesl commented
Mas @andriawan, setelah saya review kodenya, ada beberapa logic yang kurang pas bagi saya:

1. Fitur carousel, itu:
   - Tidak ada indikator jumlah slide (item carousel)-nya, sehingga ketika pengunjung buka web, mereka ngga tahu kalau ada jadwal pengajian lain selain yang yang tampil pertama
   - Tidak ada handle untuk next dan prev, sehingga pengunjung harus menunggu 5 detik untuk ke next slidenya. Dan mereka mungkin ngga sadar bahwa akan ada next slide.
2. Terlalu banyak variable yang di-pass dari class livewire, padahal bisa langsung diset di view saja. 
3. Ketika hari ini adalah hari jumat, yang tampil hanya jadwal khatib saja. Jika ada jadwal pengajian rutin, tidak tampil di sini (harapannya tetap tampil jadwal pengajian rutin juga). Bagian ini mungkin saya yang kurang detail menjabarkan deskripsi tasknya.

Baik, untuk 3 hal itu, saya akan coba bikin code suggestion yang nanti bisa mas coba.

Terima kasih sebelumnya mas

2023-09-17 16:25 UTC, andriawan commented
Terima kasih untuk feedbacknya mas @nafiesl .

Saya mencoba menanggapi 3 point di atas.

1. Untuk carousel, saya coba seminimal mungkin interaksi elemen. Menurut saya data di beranda adalah data yang disajikan secara ringkas sehingga pengunjung tidak terlalu terbebani dengan banyak informasi. Namun, jika membuat pengunjung bingung, bisa kita tambahkan indikator menjelaskan card tersebut memiliki informasi lebih.

2. Untuk point ini, saya pribadi lebih memilih view blade agar seminimal mungkin memiliki logic kode panjang sehingga akan sulit untuk dibaca. Saya memilih menempatkan kode tersebut sebagai prop livewire agar lebih tertata dan kedepannya mungkin akan lebih mudah untuk refactoring.

3. Sejauh yang saya sudah test di lokal, untuk hari jumat, informasi data khatib dan pengajian lainnya di hari tersebut muncul. Mungkin nanti akan saya tambah test case detail mengenai masalah ini.

2023-09-17 16:29 UTC, nafiesl commented
mas @andriawan, bentar mas, saya bikin code suggestion dulu ya. Terutama untuk carouselnya, jangan ditambahin dulu, saya masih timbang-timbang dulu. Nanti saya komen lagi mas

2023-09-18 02:21 UTC, nafiesl requested changes
Mas @andriawan saya ada beberapa review untuk PR ini. Silakan mas.

2023-09-18 02:21 UTC, nafiesl commented on resources/views/livewire/public_home/today_lecturing_schedules.blade.php
> +</div>
Halo mas @andriawan, setelah saya susun-susun templatenya, saya ingin tampilannya seperti ini mas.

### Screenshot

<details>
<summary>*Hari Jumat*</summary>

Kondisi ada pengajian ba'da subuh, shalat jumat dan ba'da ashar

![screen_2023-09-18_001](https://github.com/buku-masjid/buku-masjid/assets/8721551/c2a35200-570e-4141-9138-3fed3c41f5eb)
</details>

<details>
<summary>Jika *tidak ada jadwal*</summary>

Tampil seperti ini.

![screen_2023-09-18_002](https://github.com/buku-masjid/buku-masjid/assets/8721551/b3242be0-ab73-448b-82c6-96e241ac45dd)
</details>

### Summary
1. Tidak perlu menggunakan carousel, cukup tampilkan semua pengajian yang terjadwal hari itu. Ini untuk memperjelas informasi jadwal. Karena yang cari info jadwal pengajian biasanya juga bapak/ibu senior separuh baya. Melihat informasi dengan scroll ke atas dan ke bawah lebih mudah bagi mereka dibandingkan *swipe* kiri dan kanan (melihat slide)
2. Tombol "Lihat detail" cukup 1 di judul section
3. Untuk card title kita bisa langsung panggil lang, ini untuk memangkas definisi variable di class livewire component

Berikut kode untuk viewnya. Silakan tanggapannya mas.

```suggestion
<div class="page-header">
    <h3 class="page-title">{{ __('lecturing_schedule.public_schedule') }} {{ __('time.today') }}</h3>
    <div class="page-options d-flex">
        @if (!$lecturingSchedules->isEmpty())
            <a class="btn btn-sm btn-success" href="{{ route('public_schedules.index') }}" role="button">{{ __('app.show') }}</a>
        @endif
    </div>
</div>

@forelse($lecturingSchedules as $index => $lecturingSchedule)
<div class="card">
    <div class="card-header">
        <h3 class="card-title">
            {{ __('lecturing_schedule.audience_'.$lecturingSchedule->audience_code) }}
        </h3>
    </div>
    <table class="table table-sm mb-0">
        <tbody>
            @if ($lecturingSchedule->audience_code != $audienceFriday)
                <tr>
                    <td class="col-4">{!! config('lecturing.emoji.lecturing') !!} {{ __('lecturing_schedule.lecturing') }}</td>
                    <td><strong>{{ $lecturingSchedule->day_name }}, {{ $lecturingSchedule->time_text }}</strong></td>
                </tr>
            @endif
            <tr>
                <td>{!! config('lecturing.emoji.time') !!} {{ __('lecturing_schedule.time') }}</td>
                <td>{{ $lecturingSchedule->audience_code === $audienceFriday ? $lecturingSchedule->start_time : $lecturingSchedule->time }}</td>
            </tr>
            <tr>
                <td>{!! config('lecturing.emoji.lecturer') !!} {{ $lecturerName[$lecturingSchedule->audience_code] }}</td>
                <td>{{ $lecturingSchedule->lecturer_name }}</td>
            </tr>
        </tbody>
    </table>
</div>
@empty
{{ __('lecturing_schedule.today_empty') }}.
@endforelse

```

2023-09-18 02:21 UTC, nafiesl commented on app/Http/Livewire/PublicHome/TodayLecturingSchedules.php
> +    }
Bagian ini aman untuk kita hapus karena variablenya tidak dipakai lagi di view.

```suggestion
```

2023-09-18 02:21 UTC, nafiesl commented on app/Http/Livewire/PublicHome/TodayLecturingSchedules.php
> +        $this->isFriday = strtolower(Carbon::today()->format('l')) === LecturingSchedule::AUDIENCE_FRIDAY;
Tidak digunakan di view.
```suggestion
```

2023-09-18 02:21 UTC, nafiesl commented on app/Http/Livewire/PublicHome/TodayLecturingSchedules.php
> +        $this->audienceCodes = $this->getAudienceCodeList();
Bagian query ini, tidak perlu difilter lagi untuk meng-khususkan hari jadwal Khatib Jumat.
```suggestion
        $this->lecturingSchedules = $lecturingScheduleQuery->get();
```

2023-09-18 02:21 UTC, nafiesl commented on app/Http/Livewire/PublicHome/TodayLecturingSchedules.php
> +    public $isFriday;
Sebagian besar variable tidak digunakan di view.
```suggestion
    public $lecturingSchedules = [];
```

2023-09-18 02:49 UTC, nafiesl commented
Btw mas @andriawan, untuk nge-test fiturnya yang hari jumat, mas bisa insert ini ke databasenya:
```
INSERT INTO `lecturing_schedules` (`id`, `audience_code`, `date`, `start_time`, `end_time`, `time_text`, `lecturer_name`, `title`, `book_title`, `book_writer`, `book_link`, `video_link`, `audio_link`, `description`, `is_off`, `creator_id`, `created_at`, `updated_at`) VALUES (27, 'muslimah', '2023-07-21', '16:30', NULL, 'Ba\'da Ashar', 'Fulanah, S. Pd., M. Pd.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, '2023-08-25 22:40:43', '2023-08-25 22:40:43');
INSERT INTO `lecturing_schedules` (`id`, `audience_code`, `date`, `start_time`, `end_time`, `time_text`, `lecturer_name`, `title`, `book_title`, `book_writer`, `book_link`, `video_link`, `audio_link`, `description`, `is_off`, `creator_id`, `created_at`, `updated_at`) VALUES (31, 'friday', '2023-07-21', '12:29', NULL, NULL, 'H. Fulan, SH., S. Pd', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, '2023-08-25 22:42:22', '2023-08-25 22:42:22');
INSERT INTO `lecturing_schedules` (`id`, `audience_code`, `date`, `start_time`, `end_time`, `time_text`, `lecturer_name`, `title`, `book_title`, `book_writer`, `book_link`, `video_link`, `audio_link`, `description`, `is_off`, `creator_id`, `created_at`, `updated_at`) VALUES (41, 'public', '2023-07-21', '06:00', NULL, 'Ba\'da Subuh', 'Prof. DR. H. Fulan, M. Pd.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, '2023-08-25 22:46:33', '2023-08-25 22:46:33');
```
Kemudian di method `TodayLecturingSchedules@mount()`, dikasih gini untuk mock tanggal hari ini ke tanggal `2023-07-21`

![screen_2023-09-18_005](https://github.com/buku-masjid/buku-masjid/assets/8721551/f0d151b3-5731-4b8b-8a3d-0724ff0b29ea)

2023-09-18 03:41 UTC, andriawan commented on resources/views/livewire/public_home/today_lecturing_schedules.blade.php
> +</div>
baik mas @nafiesl. jika behavior dan data demografis user sudah dapat ditentukan (dala hal ini bapak/ibu senior) yang cenderung kurang familiar dengan teknologi, saya setuju untuk membuat UI lebih sederhana.

2023-09-18 03:41 UTC, andriawan commented on app/Http/Livewire/PublicHome/TodayLecturingSchedules.php
> +    }
oke siap mas

2023-09-18 03:43 UTC, andriawan commented
> Btw mas @andriawan, untuk nge-test fiturnya yang hari jumat, mas bisa insert ini ke databasenya:
> 
> ```
> INSERT INTO `lecturing_schedules` (`id`, `audience_code`, `date`, `start_time`, `end_time`, `time_text`, `lecturer_name`, `title`, `book_title`, `book_writer`, `book_link`, `video_link`, `audio_link`, `description`, `is_off`, `creator_id`, `created_at`, `updated_at`) VALUES (27, 'muslimah', '2023-07-21', '16:30', NULL, 'Ba\'da Ashar', 'Fulanah, S. Pd., M. Pd.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, '2023-08-25 22:40:43', '2023-08-25 22:40:43');
> INSERT INTO `lecturing_schedules` (`id`, `audience_code`, `date`, `start_time`, `end_time`, `time_text`, `lecturer_name`, `title`, `book_title`, `book_writer`, `book_link`, `video_link`, `audio_link`, `description`, `is_off`, `creator_id`, `created_at`, `updated_at`) VALUES (31, 'friday', '2023-07-21', '12:29', NULL, NULL, 'H. Fulan, SH., S. Pd', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, '2023-08-25 22:42:22', '2023-08-25 22:42:22');
> INSERT INTO `lecturing_schedules` (`id`, `audience_code`, `date`, `start_time`, `end_time`, `time_text`, `lecturer_name`, `title`, `book_title`, `book_writer`, `book_link`, `video_link`, `audio_link`, `description`, `is_off`, `creator_id`, `created_at`, `updated_at`) VALUES (41, 'public', '2023-07-21', '06:00', NULL, 'Ba\'da Subuh', 'Prof. DR. H. Fulan, M. Pd.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, '2023-08-25 22:46:33', '2023-08-25 22:46:33');
> ```
> 
> Kemudian di method `TodayLecturingSchedules@mount()`, dikasih gini untuk mock tanggal hari ini ke tanggal `2023-07-21`
> 
> ![screen_2023-09-18_005](https://user-images.githubusercontent.com/8721551/268546443-f0d151b3-5731-4b8b-8a3d-0724ff0b29ea.jpg)

benar mas, saya juga sudah terapakan di unit test untuk mengubah carbon datenya, mungkin untuk lebih meyakinkan memang perlu dicek dari UI browser langsung. akan saya coba terapkan mas.

2023-09-18 04:11 UTC, andriawan commented on app/Http/Livewire/PublicHome/TodayLecturingSchedules.php
> +        $this->audienceCodes = $this->getAudienceCodeList();
ini memungkinkan admin insert data dengan code friday tapi dengan date di luar hari jumat mas @nafiesl ?

2023-09-19 14:36 UTC, nafiesl approved these changes
Mas @andriawan, saya udah sip ini dengan fitur dan testnya. Ada sedikit typo dan style update minor mas. Habis itu kita merge :+1: 

Makasih banyak ni mas Andri.

2023-09-19 14:36 UTC, nafiesl commented on app/Http/Livewire/PublicHome/TodayLecturingSchedules.php
> +            LecturingSchedule::AUDIENCE_MUSLIMAH => __('lecturing_schedule.lecturer_name')
```suggestion
            LecturingSchedule::AUDIENCE_MUSLIMAH => __('lecturing_schedule.lecturer_name'),
```

2023-09-19 14:36 UTC, nafiesl commented on resources/lang/en/lecturing_schedule.php
> +    'friday_lecturing_schedule' => 'Friday Lecturing',
Ini kita ngga pakai lagi mas, bisa dihapus saja.
```suggestion
```

2023-09-19 14:36 UTC, nafiesl commented on resources/lang/id/lecturing_schedule.php
> +    'friday_lecturing_schedule' => 'Khatib Jumat',
Ini kita ngga pakai lagi mas, bisa dihapus saja.
```suggestion
```

2023-09-19 14:36 UTC, nafiesl commented on resources/views/guest/welcome.blade.php
> +@endsection
Tambahkan empty line ending
```suggestion
@endforelse

```

2023-09-19 14:36 UTC, nafiesl commented on resources/views/livewire/public_home/today_lecturing_schedules.blade.php
> +@endforelse
Tambahkan empty line ending
```suggestion
@endforelse

```

2023-09-19 14:36 UTC, nafiesl commented on tests/Feature/Livewire/PublicHome/TodayLecturingSchedulesTest.php
> +    public function user_can_see_firday_lecturing_today_card()
Typo
```suggestion
    public function user_can_see_friday_lecturing_today_card()
```

2023-09-19 14:57 UTC, merged