Lengkapi jadwal petugas jum'at #34
buku-masjid/buku-masjid pull request #42
Opened 2024-02-14 13:25 UTC by thirthfamous

reference dari [Lengkapi Petugas Jadwal Jumat](https://github.com/buku-masjid/buku-masjid/issues/34)

2024-02-14 14:21 UTC, thirthfamous commented
- [ ]  Tambahkan informasi nama **Imam** dan **Muadzin** pada halaman detail jadwal khatib
- [x]  Tambahkan field **Imam** dan **Muadzin** pada halaman input jadwal khatib
- [x]  Tambahkan field **Imam** dan **Muadzin** pada halaman edit jadwal khatib
- [x]  Tambahkan migration untuk kolom baru `lecturings.imam_name` dan `lecturings.muadzin_name`
- [ ]  Update tampilan informasi khatib jumat pada halaman publik menu jadwal
- [ ]  Update tampilan informasi khatib jumat pada halaman beranda publik
- [ ]  Pastikan tampilan mobile juga ter-update informasi Imam dan Khatib
- [ ]  Update automated testing terkait fitur ini

2024-02-14 23:30 UTC, thirthfamous commented
@nafiesl done mas, boleh tolong review
saya gabisa assign as reviewer di githubnya

2024-02-17 15:49 UTC, nafiesl requested changes
mas @thirthfamous great PR mas, lengkap dengan update testing dan tambahan testingnya. terima kasih.

Secara fitur saya cek sudah cocok. Kemudian untuk kodenya, ini saya ada beberapa review mas.

Mohon dibantu perbaiki ya mas.

2024-02-17 15:49 UTC, nafiesl commented on resources/views/public_schedules/_single_friday.blade.php
> +            @endif
mas @thirthfamous bagian juga diperlukan pada file ini:
[resources/views/lecturings/_single_friday.blade.php](https://github.com/buku-masjid/buku-masjid/blob/master/resources/views/lecturings/_single_friday.blade.php)

2024-02-17 15:49 UTC, nafiesl commented on tests/Feature/Livewire/PublicHome/DailyLecturingsTest.php
> +        $lecturing = Lecturing::first();
Bagian ini mestinyat tidak perlu, cukup di baris sebelumnya kita beri seperti ini:
```
Carbon::setTestNow('2023-09-16');
$lecturing = factory(Lecturing::class)->create([
    'audience_code' => Lecturing::AUDIENCE_FRIDAY,
]);
factory(Lecturing::class)->create();
```

```suggestion
```

2024-02-17 15:49 UTC, nafiesl commented on tests/Feature/Livewire/PublicHome/DailyLecturingsTest.php
> -        Carbon::setTestNow();
Bagian ini kita jangan hapus mas, karena kita harus me-reset Carbon agar tidak ada pengaruh ke berikutnya.

2024-02-17 15:49 UTC, nafiesl commented on tests/Feature/PublicSchedule/PublicScheduleTest.php
> +        $this->seeText($lecturing->muadzin_name);
Tolong tambahkan bagian reset Carbon ini ya di semua testingnya mas.

```suggestion
        $this->seeText($lecturing->muadzin_name);
        Carbon::setTestNow();
```

2024-02-17 15:49 UTC, nafiesl commented on database/migrations/2024_02_14_213435_add_imam_and_muadzin_name_in_lecturings_table.php
> +    }
mas @thirthfamous kita mau terapkan metode seperti di PR #30, tepatnya commit [0988483](https://github.com/buku-masjid/buku-masjid/pull/30/commits/0988483d794ac82bce9a242850aa41154715e975). Jadi

1. Bagian `up()` dan `down()` kita beri if-statement untuk cek apakah kolomnya sudah ada atau belum
2. Kemudian pada file `2023_08_25_103840_create_lecturings_table.php`, kita tambahkan 3 kolom ini sesuai urutannya.

Begini suggestion saya:
```suggestion
    public function up(): void
    {
        if (!Schema::hasColumn('lecturings', 'imam_name')) {
            Schema::table('lecturings', function (Blueprint $table) {
                $table->string('imam_name', 60)->nullable()->after('lecturer_name');
            });
        }
        if (!Schema::hasColumn('lecturings', 'muadzin_name')) {
            Schema::table('lecturings', function (Blueprint $table) {
                $table->string('muadzin_name', 60)->nullable()->after('lecturer_name');
            });
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        if (Schema::hasColumn('lecturings', 'imam_name')) {
            Schema::table('lecturings', function (Blueprint $table) {
                $table->dropColumn('imam_name');
            });
        }
        if (Schema::hasColumn('lecturings', 'muadzin_name')) {
            Schema::table('lecturings', function (Blueprint $table) {
                $table->dropColumn('muadzin_name');
            });
        }
    }
```

2024-02-21 13:56 UTC, thirthfamous commented
mas @nafiesl saya lihat untuk field `lecturings.title` udah ada sebelumnya
<img width="874" alt="image" src="https://github.com/buku-masjid/buku-masjid/assets/30696403/925e3ecb-6874-428b-b778-681dac56b584">

2024-02-21 15:05 UTC, nafiesl approved these changes
Sip ini mas @thirthfamous makasih banyak kontribusinya, kita merge.

2024-02-21 15:06 UTC, nafiesl commented
> mas @nafiesl saya lihat untuk field `lecturings.title` udah ada sebelumnya <img alt="image" width="874" src="https://private-user-images.githubusercontent.com/30696403/306647217-925e3ecb-6874-428b-b778-681dac56b584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjgyNTAsIm5iZiI6MTcwODUyNzk1MCwicGF0aCI6Ii8zMDY5NjQwMy8zMDY2NDcyMTctOTI1ZTNlY2ItNjg3NC00MjhiLWI3NzgtNjgxZGFjNTZiNTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE1MDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MTk2NzQyN2IyYjhjN2ZjMGRlYmRkZjg1ZmM5NzcyNjEyMmY5ZmQwMTJlZjg1ZWNlZmIxOGI0YzgxM2YzN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ZNudqGqMuBL5_lzYfCsPTmZckNF6Rpm3T8dhGhOrOM">

Iya bener mas @thirthfamous ternyata sudah ada, cuman label nya `Pembahasan` nanti saya  bertimbangkan lagi yang ini. Terima kasih mas.

2024-02-21 15:07 UTC, merged