ijinkan nilai setting bernilai null
buku-masjid/buku-masjid pull request #51
Opened 2024-03-14 23:30 UTC by pandigresik

Perbaikan issue #50 

[Screencast from 15-03-24 06:08:04.webm](https://github.com/buku-masjid/buku-masjid/assets/1853475/4fc7a860-dca7-4645-a111-6ab3d60418f9)

2024-03-15 01:24 UTC, nafiesl requested changes
Mas @pandigresik saya ada 1 review sugestion bagian kodenya.

Kemudian pada fitur Setting ini kita punya unit testinya mas. Mohon bantu update juga testingnya ya. 

Testingnya di sini:
https://github.com/buku-masjid/buku-masjid/blob/master/tests/Unit/Helpers/SettingTest.php

Tambahkan 2 method test:
```
/** @test */
public function setting_can_be_set_with_a_null_value()
{
}

/** @test */
public function setting_can_get_a_null_value()
{
}
```

2024-03-15 01:24 UTC, nafiesl commented on app/Helpers/Setting.php
> +            return $setting->value ?? $default;
Sebaiknya bagian sini jangan return `$default` karena di bawah juga return `$default`
```suggestion
            return $setting->value;
```

Untuk mengijinkan return value null, kita atur return value methodnya saja boleh string atau null
```
public function get(string $key, $default = ''): string | null
```

2024-03-15 23:53 UTC, pandigresik commented on app/Helpers/Setting.php
> +            return $setting->value ?? $default;
sudah disesuaikan

2024-03-20 02:37 UTC, nafiesl approved these changes
Sudah sip ini mas @pandigresik kita merge.

Terima kasih mas.

2024-03-20 02:37 UTC, merged